name: Enforce Squash and Conventional Commits on Merge

on:
  pull_request:
    branches:
      - development
    types: [closed]

jobs:
  enforce_squash_and_conventional_commits:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to check commit messages

      - name: Get Merge Commit Message
        run: echo "MERGE_COMMIT_MESSAGE=$(git log -1 --format=%B)" >> $GITHUB_ENV

      - name: Verify Conventional Commit Format
        run: |
          echo "${{ env.MERGE_COMMIT_MESSAGE }}" | grep -qE '^(chore|feat|fix|docs):'
          if [ $? -ne 0 ]; then
            echo "ERROR: Merge commit message must start with 'chore:', 'feat:', 'fix:', or 'docs:'."
            exit 1
          fi

      - name: Verify Squash and Merge
        run: |
          if [[ "${{ github.event.pull_request.merge_method }}" != "squash" ]]; then
            echo "ERROR: Merges to the 'development' branch must use 'Squash and merge'."
            exit 1
          fi
